# version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: cv_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.7.0
    container_name: cv_mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    volumes:
      - ./mlflow_data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri file:///mlflow
      --default-artifact-root file:///mlflow/artifacts
      --allowed-hosts "*"
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: cv_frontend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - MLFLOW_TRACKING_URI=http://mlflow:5000
  #   volumes:
  #     - ./shared:/app/shared
  #   depends_on:
  #     - redis
  #     - mlflow
    
  #   restart: unless-stopped

  trainer:
    build: ./trainer
    container_name: cv_trainer
    shm_size: '4gb'
    ports:
      - "311:311"
    volumes:
      - ./datasets:/app/data
    depends_on:
      - redis
      - mlflow
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"
    

volumes:
  redis_data: